// This header file was auto-generated by ClassMate++
// Created: 16 Sep 2017 5:37:16 pm
// Copyright (c) 2017, HurleyWorks

#pragma once

static const char* RenderableBodyTypeTable[] =
    {
        "None",
        "Invalid"};

struct RenderableBodyType
{
    enum ERenderableBodyType
    {
        None,
        Fluid,

        Count,
        Invalid = Count
    };

    union {
        ERenderableBodyType name;
        unsigned int value;
    };

    RenderableBodyType (ERenderableBodyType name) :
        name (name) {}
    RenderableBodyType (unsigned int value) :
        value (value) {}
    RenderableBodyType() :
        value (Invalid) {}
    operator ERenderableBodyType() const { return name; }
    const char* toString() const { return RenderableBodyTypeTable[value]; }
};

