// This source file was auto-generated by ClassMate++
// Created: 17 Aug 2019 3:42:21 pm
// Copyright (c) 2019, HurleyWorks

#include "berserkpch.h"
#include "OptixLayer.h"

// ctor
OptixLayer::OptixLayer (const PropertyService& properties, CameraHandle& camera)
	: RenderLayer(properties, camera)
{	
	
}

// dtor
OptixLayer::~OptixLayer ()
{	
}

void OptixLayer::onAttach()
{
	RenderLayer::attached = true;
}

void OptixLayer::onDetach()
{
	RenderLayer::attached = false;
}

void OptixLayer::onUpdate()
{
	
}

bool OptixLayer::onInput(const InputEventRef& input)
{
	return false;
}

