// This source file was auto-generated by ClassMate++
// Created: 1 Jun 2015 9:46:20 am
// Copyright (c) 2015, HurleyWorks

#include "ActiveFramework.h"

// shutdown
void ActiveFramework::shutdown()
{
    LOG (DBUG) << _FN_;
    dreamer.done();
    render.done();
    io.done();
    geometry.done();
    world.done();
}
