// This header file was auto-generated by ClassMate++
// Created: 24 Jul 2019 5:49:34 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

#include <qms_core/qms_core.h>

class Dreamer; // forward decl for impl

class ActiveDreamer
{
    // The Active Object design pattern decouples method execution from
    // method invocation to enhance concurrency and simplify synchronized
    // access to an object that resides in its own thread of control.

 public:
    ActiveDreamer();
    ~ActiveDreamer();

    // messaging
    MsgSender getMessenger() { return incoming; }
    void done() { getMessenger().send (qms::clear_queue()); }

    bool terminate() { return windowClosed; }

 private:
    std::unique_ptr<Dreamer> impl;

    // messaging
    MsgReceiver incoming;

    // message arguments
    size_t frameNumber = 0;
    MessageService messengers;
    PropertyService properties;
    bool windowClosed = false;
    std::vector<std::string> dropList;
    uint32_t lastPhysicsFrame = 0;

    // state functions
    std::thread stateThread;
    void (ActiveDreamer::*state)();
    void waitingForMessages();
    void init();
    void onTick();
    void onWindowClose();
    void onDrop();
   

    // state thread function
    void executeState();
    void start();

    bool shutdown = false;

}; // end class ActiveDreamer