// This source file was auto-generated by ClassMate++
// Created: 31 Jul 2019 4:12:49 pm
// Copyright (c) 2019, HurleyWorks

#include "Dreamer.h"

void Dreamer::init (MessageService messengers, const PropertyService& properties)
{
    this->messengers = messengers;
    this->properties = properties;
}

void Dreamer::tick (size_t frameNumber)
{
}
