// This header file was auto-generated by ClassMate++
// Created: 31 Jul 2019 4:12:49 pm
// Copyright (c) 2019, HurleyWorks

#pragma once
#include <qms_core/qms_core.h>

class Dreamer
{
 public:
    Dreamer() = default;
    ~Dreamer() = default;

    void init (MessageService messengers, const PropertyService& properties);
    void tick (size_t frameNumber);

 private:
    MessageService messengers;
    PropertyService properties;

}; // end class Dreamer
