// This header file was auto-generated by ClassMate++
// Created: 5 Sep 2020 6:49:18 pm
// Copyright (c) 2020, HurleyWorks

#pragma once

using juce::String;
using juce::Time;

class CudaCompiler
{
public:
	using FileInfoMap = std::unordered_map<String, String>;

public:
	CudaCompiler();
	~CudaCompiler();

	void compile(const PropertyService& properties);
	void verifyPath(const String& path);

private:
	FileInfoMap fileInfo;

}; // end class CudaCompiler
