// This header file was auto-generated by ClassMate++
// Created: 9 Aug 2020 3:08:12 pm
// Copyright (c) 2020, HurleyWorks

#pragma once

using sabi::RenderableNode;

class MotionHandler
{
 public:
    MotionHandler() = default;
    ~MotionHandler() = default;

    void initialize (MoojiStateRef& state);
    void createMotionKeys (RenderableNode& node, InstanceRef& inst);
    uint32_t getKeyCount() const { return numMotionKeys; }
    void computeMotionAABBs();
    void updateMotionAABBs();
    void updateMotion();

 private:
    MoojiStateRef state = nullptr;
    std::vector<TransforM> transformsObject;
    std::vector<AABB> baseAABBsObject;
    uint32_t numMotionKeys = 0;

}; // end class MotionHandler
