// This source file was auto-generated by ClassMate++
// Created: 8 Sep 2020 8:44:40 pm
// Copyright (c) 2020, HurleyWorks

// ctor
NoiseHandler::NoiseHandler (OptiXStateRef state) :
    state (state)
{
}

// dtor
NoiseHandler::~NoiseHandler()
{
}
