// This header file was auto-generated by ClassMate++
// Created: 8 Sep 2020 8:44:40 pm
// Copyright (c) 2020, HurleyWorks

#pragma once

using NoiseHandlerRef = std::shared_ptr<class NoiseHandler>;

class NoiseHandler
{
 public:
    static NoiseHandlerRef create (OptiXStateRef state) { return std::make_shared<NoiseHandler> (state); }

 public:
    NoiseHandler (OptiXStateRef state);
    ~NoiseHandler();

 private:
    OptiXStateRef state = nullptr;

}; // end class NoiseHandler
