// This header file was auto-generated by ClassMate++
// Created: 11 Sep 2020 3:08:51 pm
// Copyright (c) 2020, HurleyWorks

#pragma once

using sabi::RenderableNode;

class PickHandler
{
 public:
    PickHandler (OptiXStateRef state);
    ~PickHandler();

    PickingData* getDevicePtr() { return pickDataBuffer.getDevicePointer(); }
    RenderableNode getPick();

 private:
    OptiXStateRef state;
    cudau::TypedBuffer<Shared::PickingData> pickDataBuffer;

}; // end class PickHandler
