// This source file was auto-generated by ClassMate++
// Created: 16 Sep 2017 12:15:26 pm
// Copyright (c) 2017, HurleyWorks

#include "WorldOps.h"
#include "WorldCore.h"
#include "ActiveWorld.h"

using namespace qms;

// ctor
ActiveWorld::ActiveWorld() :
    impl (new WorldCore()),
    stateThread()
{
    // https://rafalcieslak.wordpress.com/2014/05/16/c11-stdthreads-managed-by-a-designated-class/
    start();
}

// dtor
ActiveWorld::~ActiveWorld()
{
    done();
    if (stateThread.joinable())
        stateThread.join();
}

// start
void ActiveWorld::start()
{
    stateThread = std::thread (&ActiveWorld::executeState, this);
}

// executeState
void ActiveWorld::executeState()
{
    LOG (DBUG) << "ActiveWorld thread is starting up";

    state = &ActiveWorld::waitingForMessages;

    while (!shutdown)
    {
        (this->*state)();
    }

    LOG (DBUG) << "ActiveWorld thread is shutting down";
}

// waitingForMessages
void ActiveWorld::waitingForMessages()
{
    incoming.wait()
        .handle<qms::clear_queue> ([&] (qms::clear_queue const& msg) {
            shutdown = true;
        })
        .handle<QMS::init> ([&] (QMS::init const& msg) {
            messengers = msg.messengers;
            properties = msg.properties;
            state = &ActiveWorld::init;
        })
        .handle<QMS::createNewRenderable> ([&] (QMS::createNewRenderable const& msg) {
            renderableData = msg.data;
            state = &ActiveWorld::createNewRenderable;
        })
        .handle<QMS::createInstanceClump> ([&] (QMS::createInstanceClump const& msg) {
            instanceCount = msg.count;
            state = &ActiveWorld::makeInstanceClump;
        })
        .handle<QMS::tick> ([&] (QMS::tick const& msg) {
            frameNumber = msg.frame;
            state = &ActiveWorld::onTick;
        });
}

// init
void ActiveWorld::init()
{
    impl->init (messengers, properties);
    state = &ActiveWorld::waitingForMessages;
}

// onTick
void ActiveWorld::onTick()
{
    try
    {
        impl->tick (frameNumber);
    }
    catch (std::exception& e)
    {
        LOG (CRITICAL) << e.what();
        messengers.dreamer.send (QMS::onError (e.what()));
    }
    catch (...)
    {
        LOG (CRITICAL) << "Caught unknown exception!";
        messengers.dreamer.send (QMS::onError ("Caught unknown exception!"));
    }

    state = &ActiveWorld::waitingForMessages;
}

void ActiveWorld::createNewRenderable()
{
    try
    {
        impl->createNewRenderable (renderableData);
    }
    catch (std::exception& e)
    {
        LOG (CRITICAL) << e.what();
        messengers.dreamer.send (QMS::onError (e.what()));
    }
    catch (...)
    {
        LOG (CRITICAL) << "Caught unknown exception!";
        messengers.dreamer.send (QMS::onError ("Caught unknown exception!"));
    }
    state = &ActiveWorld::waitingForMessages;
}

void ActiveWorld::makeInstanceClump()
{
    try
    {
        impl->worldOps()->createInstanceClump (instanceCount);
    }
    catch (std::exception& e)
    {
        LOG (CRITICAL) << e.what();
        messengers.dreamer.send (QMS::onError (e.what()));
    }
    catch (...)
    {
        LOG (CRITICAL) << "Caught unknown exception!";
        messengers.dreamer.send (QMS::onError ("Caught unknown exception!"));
    }
    state = &ActiveWorld::waitingForMessages;
}
