// This header file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#pragma once

using sabi::RenderableData;
using sabi::RenderableNode;

class WorldCore
{
 public:
    WorldCore();
    ~WorldCore();

    void init (MessageService messengers, const PropertyService& properties);
    void tick (size_t frameNumber);
    void createNewRenderable (const RenderableData& d);

    WorldOps* worldOps() { return &ops; }

 private:
    MessageService messengers;
    PropertyService properties;

    RenderableNode world = nullptr;
    WorldOps ops;

}; // end class WorldCore
