// This source file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#include "WorldCore.h"

using sabi::RenderableNode;
using sabi::RenderableState;
using sabi::WorldComposite;
using sabi::WorldItem;
using sabi::PRenderableState;

// ctor
WorldCore::WorldCore() :
    world (WorldComposite::create()),
    ops (world)
{
    world->setName ("TheWorld");
}

// dtor
WorldCore::~WorldCore()
{
}

// init
void WorldCore::init (MessageService messengers, const PropertyService& properties)
{
    this->messengers = messengers;
    this->properties = properties;

    ops.init (messengers, properties);
}

// tick
void WorldCore::tick (size_t frameNumber)
{
    // Everyone needs a tick
}

void WorldCore::createNewRenderable (const RenderableData& d)
{
    RenderableNode node = WorldItem::create();
    node->setClientID (d.clientID);
    node->setDescription (d.desc);
    node->setMesh (d.mesh);
    node->setSpacetime (d.spacetime);
    node->setState (d.state);
    node->setName (d.name);

    // everyone is visible and pickable to start
    node->getState().state |= PRenderableState::Pickable;
    node->getState().state |= PRenderableState::Visible;

    world->addChild (node);

    // send it to the Renderer
    messengers.render.send (QMS::addNodeToRenderer (node));
}
