// This header file was auto-generated by ClassMate++
// Created: 16 Sep 2017 12:15:26 pm
// Copyright (c) 2017, HurleyWorks

#pragma once

using sabi::CameraHandle;
using sabi::RenderableWeakRef;
using sabi::InputEventRef;

class RenderCore; // forward decl for impl

class ActiveRender
{
    // The Active Object design pattern decouples method execution from
    // method invocation to enhance concurrency and simplify synchronized
    // access to an object that resides in its own thread of control.

 public:
    ActiveRender();
    ~ActiveRender();

    // messaging
    MsgSender getMessenger() { return incoming; }
    void done() { getMessenger().send (qms::clear_queue()); }

 private:
    std::unique_ptr<RenderCore> impl;

    // messaging
    MsgReceiver incoming;

    // message arguments
    MessageService messengers;
    PropertyService properties;
    uint32_t frameNumber = 0;
    CameraHandle camera = nullptr;
    RenderableWeakRef weakNode;
    InputEventRef input = nullptr;

    // state functions
    std::thread stateThread;
    void (ActiveRender::*state)();
    void waitingForMessages();
    void init();
    void onTick();
    void initEngine();
    void renderNextFrame();
    void addRenderableNode();
    void onInput();

    // state thread function
    void executeState();
    void start();

    bool shutdown = false;

}; // end class ActiveRender
