// This source file was auto-generated by ClassMate++
// Created: 7 Sep 2020 8:08:36 pm
// Copyright (c) 2020, HurleyWorks


void GeometryInstance::finalize(GeometryInstance* p)
{
	p->optixGeomInst.destroy();
	p->triangleBuffer.finalize();
	delete p;
}

void GeometryGroup::finalize(GeometryGroup* p)
{
    p->optixGasMem.finalize();
    p->optixGAS.destroy();
    delete p;
}

void GeometryGroup::propagateMarkDirty() const
{
    for (const auto& parentWRef : parentInsts)
    {
        InstanceRef parent = parentWRef.lock();
        parent->propagateMarkDirty();
    }
}

void Instance::finalize(Instance* p)
{
    p->optixInst.destroy();
    delete p;
}

void Instance::propagateMarkDirty() const 
{
    for (const auto& parentWRef : parentGroups) {
        GroupRef parent = parentWRef.lock();
        parent->propagateMarkDirty();
    }
}

void Group::finalize(Group* p) 
{
    p->optixInstanceBuffer.finalize();
    p->optixIasMem.finalize();
    p->optixIAS.destroy();
    delete p;
}
void Group::propagateMarkDirty() const
{
    optixIAS.markDirty();
    for (const auto& parentWRef : parentInsts) {
        InstanceRef parent = parentWRef.lock();
        parent->propagateMarkDirty();
    }
}
