// This header file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#pragma  once

using sabi::CameraHandle;
using sabi::RenderableNode;

class RenderCore
{

public:
	RenderCore() = default;
   ~RenderCore();

	void init(MessageService messengers, const PropertyService& properties);
	void tick(size_t frameNumber) {}
	void initEngine(CameraHandle& camera);
	void render(CameraHandle& camera, uint32_t frameNumber);
	void onInput(InputEvent& input);
	void addRenderableNode(RenderableNode& node);

private:
	MessageService messengers;
	PropertyService properties;

    CudaCompiler nvcc;

	OptiXStateRef state = nullptr;
	MeshHandlerRef mesh = nullptr;
	MaterialHandlerRef material = nullptr;
	MotionHandlerRef motion = nullptr;
    NoiseHandlerRef noise = nullptr;
    PipelineHandlerRef pipeline = nullptr;
    SceneHandlerRef scene = nullptr;
    IRendererRef renderer = nullptr;

}; // end class RenderCore

