// This header file was auto-generated by ClassMate++
// Created: 11 Sep 2015 7:51:05 am
// Copyright (c) 2015, HurleyWorks

#pragma once

namespace qms
{
    static const char* QmsIDTable[] =
        {
            "TopPriority",
            "ClearQueue",

            // dreamer messages
            "Init",
            "OnError",
            "OnInput",
            "Tick",

            // IO messages
            "LoadMesh",
            "ProcessLoadData",

            // World messages
            "CreateNewRenderable",
            "DeselectAll",
            "CreateInstanceClump",

            // Geometry messages
            "MakeGroundPlane",

            // render messages
            "RenderNextFrame",
            "AddNodeToRenderer",
            "InitRenderEngine",

            "Invalid"};

    struct QmsID
    {
        enum EQmsID
        {
            TopPriority = 1,
            ClearQueue,

            // dreamer messages
            Init,
            OnError,
            OnInput,
            Tick,

            // IO messages
            LoadMesh,
            ProcessLoadData,

            // World messages
            CreateNewRenderable,
            DeselectAll,
            CreateInstanceClump,

            // Geometry messages
            MakeGroundPlane,

            // render messages
            RenderNextFrame,
            AddNodeToRenderer,
            InitRenderEngine,

            Count,
            Invalid = Count
        };

        union
        {
            EQmsID name;
            unsigned int value;
        };

        QmsID (EQmsID name) :
            name (name) {}
        QmsID (unsigned int value) :
            value (value) {}
        QmsID() :
            value (Invalid) {}
        operator EQmsID() const { return name; }
        const char* toString() const { return QmsIDTable[value]; }
    };

    struct clear_queue
    {
        QmsID id = QmsID::ClearQueue;
    };

} // namespace qms
