// This header file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#pragma once

using Eigen::Vector2f;
using Eigen::Vector3f;
using sabi::LoadData;
using sabi::Material;
using sabi::MeshBuffersHandle;
using sabi::RenderableData;
using sabi::LoadStrategyHandle;

class GeoCore
{
 public:
    GeoCore() = default;
    ~GeoCore() = default;

    void init (MessageService messengers, const PropertyService& properties);
    void tick (size_t frameNumber);

    void processLoadData (const LoadData&& loadData);
    void createGroundPlane (const Vector2f& size = Vector2f (100.0f, 100.0f));

 private:
    MessageService messengers;
    PropertyService properties;
    LoadStrategyHandle loadStrategy = nullptr;

    void processRenderableData (RenderableData& d);
    void createQuad (const Vector2f& size, const Vector3f& position,
                     const Vector3f& direction, const Material& material,
                     const std::string& name = "unnamed quad");
}; // end class GeoCore
